#
# SPDX-License-Identifier: LGPL-2.1-or-later
# See LICENSE file for details.
#
# Copyright 2012-2026 Hazendaz.
#

# a property file that should not be compressed,...
# see https://github.com/davidB/yuicompressor-maven-plugin/issues/19

prop.fake=${prop.fake}
prop.rf01=${value.rf01}
