/*
 * YuiCompressor Maven plugin
 *
 * Copyright 2012-2026 Hazendaz.
 *
 * Licensed under the GNU Lesser General Public License (LGPL),
 * version 2.1 or later (the "License").
 * You may not use this file except in compliance with the License.
 * You may read the licence in the 'lgpl.txt' file in the root folder of
 * project or obtain a copy at
 *
 *     https://www.gnu.org/licenses/lgpl-2.1.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.hazendaz.maven.yuicompressor_maven_plugin;

import java.lang.reflect.Field;

import org.apache.maven.plugin.MojoExecutionException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Tests for the generated {@link HelpMojo}.
 * <p>
 * The HelpMojo is generated by maven-plugin-tools and loads its metadata from
 * {@code /META-INF/maven/com.github.hazendaz.maven/yuicompressor-maven-plugin/plugin-help.xml} which is present on the
 * test classpath via {@code target/classes}.
 */
class HelpMojoTest {

    // ---------------------------------------------------------------- helpers

    /**
     * Creates a HelpMojo with its fields set via reflection.
     *
     * @param goal
     *            goal filter (may be null/empty to list all goals)
     * @param detail
     *            whether to show all parameters
     * @param lineLength
     *            display line length
     * @param indentSize
     *            indent size in spaces
     *
     * @return configured HelpMojo
     *
     * @throws Exception
     *             if reflection fails
     */
    private HelpMojo createMojo(String goal, boolean detail, int lineLength, int indentSize) throws Exception {
        final var mojo = new HelpMojo();
        setField(mojo, "goal", goal);
        setField(mojo, "detail", detail);
        setField(mojo, "lineLength", lineLength);
        setField(mojo, "indentSize", indentSize);
        return mojo;
    }

    /**
     * Sets a private field on an object via reflection.
     *
     * @param target
     *            the object to modify
     * @param fieldName
     *            the field name
     * @param value
     *            the value to set
     *
     * @throws Exception
     *             if reflection fails
     */
    private static void setField(Object target, String fieldName, Object value) throws Exception {
        Class<?> clazz = target.getClass();
        Field field = null;
        while (clazz != null) {
            try {
                field = clazz.getDeclaredField(fieldName);
                break;
            } catch (NoSuchFieldException e) {
                clazz = clazz.getSuperclass();
            }
        }
        if (field == null) {
            throw new NoSuchFieldException(fieldName);
        }
        field.setAccessible(true);
        field.set(target, value);
    }

    // ------------------------------------------------------------------ tests

    /**
     * Execute with default parameters (no goal filter, no detail) should list all plugin goals without error.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_defaultParams_listsAllGoals() throws Exception {
        final var mojo = createMojo(null, false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with default params should not throw");
    }

    /**
     * Execute with goal="compress" should display help for that specific goal only.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_withSpecificGoal_compress() throws Exception {
        final var mojo = createMojo("compress", false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with goal='compress' should not throw");
    }

    /**
     * Execute with goal="jslint" should display help for that specific goal.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_withSpecificGoal_jslint() throws Exception {
        final var mojo = createMojo("jslint", false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with goal='jslint' should not throw");
    }

    /**
     * Execute with goal="help" should display help for the help goal.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_withSpecificGoal_help() throws Exception {
        final var mojo = createMojo("help", false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with goal='help' should not throw");
    }

    /**
     * Execute with detail=true and no goal filter should show all parameters for all goals.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_detailTrue_allGoals() throws Exception {
        final var mojo = createMojo(null, true, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with detail=true should not throw");
    }

    /**
     * Execute with detail=true and a specific goal should show all parameters for that goal.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_detailTrue_specificGoal() throws Exception {
        final var mojo = createMojo("compress", true, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with detail=true and goal='compress' should not throw");
    }

    /**
     * Execute with detail=true for jslint goal should show all parameters.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_detailTrue_jslintGoal() throws Exception {
        final var mojo = createMojo("jslint", true, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with detail=true and goal='jslint' should not throw");
    }

    /**
     * Execute with lineLength &lt;= 0 should log a warning and use the default of 80.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_invalidLineLength_usesDefault() throws Exception {
        final var mojo = createMojo(null, false, 0, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with lineLength=0 should not throw");
    }

    /**
     * Execute with indentSize &lt;= 0 should log a warning and use the default of 2.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_invalidIndentSize_usesDefault() throws Exception {
        final var mojo = createMojo(null, false, 80, 0);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with indentSize=0 should not throw");
    }

    /**
     * Execute with both lineLength and indentSize invalid.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_bothInvalid_usesDefaults() throws Exception {
        final var mojo = createMojo(null, false, -1, -1);
        Assertions.assertDoesNotThrow(mojo::execute,
                "execute() with both lineLength and indentSize invalid should not throw");
    }

    /**
     * Execute with a non-existent goal still completes but outputs nothing for that goal.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_unknownGoal_noOutput() throws Exception {
        final var mojo = createMojo("nonexistent-goal", false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with unknown goal should not throw");
    }

    /**
     * Execute with a very short lineLength to exercise line-wrapping.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_shortLineLength_wrapsLines() throws Exception {
        final var mojo = createMojo(null, false, 40, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with short lineLength should not throw");
    }

    /**
     * Execute with a large indentSize and detail enabled to exercise the parameter output.
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_largeIndentSize_detail() throws Exception {
        final var mojo = createMojo("compress", true, 120, 4);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with large indent and detail should not throw");
    }

    /**
     * Execute with an empty string goal (same as null – lists all goals).
     *
     * @throws Exception
     *             if execution fails
     */
    @Test
    void testExecute_emptyGoal_listsAllGoals() throws Exception {
        final var mojo = createMojo("", false, 80, 2);
        Assertions.assertDoesNotThrow(mojo::execute, "execute() with empty goal should not throw");
    }

    /**
     * Verify that execute succeeds when the plugin-help.xml resource is on the classpath.
     *
     * @throws MojoExecutionException
     *             if execution fails unexpectedly
     */
    @Test
    void testExecute_pluginHelpXmlPresent_doesNotThrow() throws MojoExecutionException {
        final var mojo = new HelpMojo();
        Assertions.assertDoesNotThrow(mojo::execute,
                "Normal execute should succeed when plugin-help.xml is on classpath");
    }
}
